name: to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy
        run: |
          # Your build and deploy commands here
